spring.application.name=recapbot
spring.h2.console.enabled=true
spring.profiles.active=local



telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.bot.baseUrl=https://api.telegram.org

gemini.api.key=${GEMINI_API_KEY}
gemini.api.model=gemini-3.1-flash-lite
gemini.api.baseUrl=https://generativelanguage.googleapis.com/v1beta/models